apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: mysql
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        env: 
         - name: MYSQL_ROOT_PASSWORD
           valueFrom:
             secretKeyRef:
                 name: mysql-secret
                 key: mypass
         - name: MYSQL_DATABASE
           value: customer_db
        ports:
          - containerPort: 3306
        volumeMounts:
          - name: mysql-vol
            mountPath: docker-entrypoint-initdb.d
      volumes:
        - name: mysql-vol
          configMap:
            name: mysql-cm
        resources:
           requests:
               memory: 500Mi
               cpu: 500m
           limits:
               memory: 600Mi
               cpu: 600m   
