apiVersion: v1
data:
  database.sql: |
    CREATE TABLE customers (
        id INT AUTO_INCREMENT PRIMARY KEY,
        name VARCHAR(50) NOT NULL,
        email VARCHAR(100) NOT NULL,
        phone VARCHAR(15) NOT NULL,
        address TEXT NOT NULL
    );
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: mysql-cm
